# Dockerfile for setting up OakD Driver
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN pip3 install numpy pre-commit

RUN sudo apt-get remove -y libspdlog-dev libspdlog1

RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y gcc-11 \
      g++-11 \
      libgstreamer1.0-dev \
      libgstreamer-plugins-base1.0-dev

RUN mkdir -p /etc/udev/rules.d
RUN wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/main/install_dependencies.sh | sudo bash
