# fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black

  -   repo: https://github.com/pre-commit/mirrors-yapf
      rev: 'v0.32.0'
      hooks:
      -   id: yapf

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
        files: ^.*\.(|cc|cpp|h|hpp|tpp|tcc)$
        types_or: [file, c++]
